### ISSUE TITLE
Briefly document how this relates to the official RFP?

### ISSUE THREAD

**Issue by artemis-prime** [muxinc/next-video#112]
It would be great to see a word or two about any planned adoption by vercel or other collaborations around this code.

**Comment by heff** [comment]
Hi @artemis-prime, where would you expect to see this? If you've read the RFP then you know as much as I do about any other adoption plans, which is to say there aren't any as of yet. I would imagine if Vercel prioritizes video at some point we'll see some comments happen on the RFP. We also wrote the RFP, if that wasn't clear.

This project is a stand-alone version of what we'd hope to see in next.js proper some day, but until then we hope people find this project useful.

Gonna close this issue for now as I don't know that there's any more to do here but feel free to give more details on what you'd want to see.
