### ISSUE TITLE
MOV format not supported

### ISSUE THREAD

**Issue by yassineatik** [muxinc/next-video#114]
.MOV videos are not supported:
![image](https://github.com/muxinc/next-video/assets/77692478/c004c48d-56ab-4bba-979c-090d62a2b731)

**Comment by heff** [comment]
Thanks for reporting this @yassineatik. Did you happen to see any errors show in the console about processing the video?

It could be that the video wasn't processed yet and this was the player falling back to the local source. If you wait for a few minutes before trying to load the page/player (after the video has had time to process) does it work then?

**Comment by heff** [comment]
I can confirm other .mov files work, so without more info there's nothing we can do here. We can reopen if you have more info to give. Thanks!
