### ISSUE TITLE
Can't read video from youtube url

### ISSUE THREAD

**Issue by yassineatik** [muxinc/next-video#115]
I have created an API folder inside my app :

![image](https://github.com/muxinc/next-video/assets/77692478/97167b66-2273-4007-a062-0b0ce2bc4b42)

it includes this line of code :
```JavaScript
export { GET } from 'next-video/request-handler';
```

And here is the code in my component :
```JavaScript
    <Video
      src='https://www.youtube.com/watch?v=RqitwhLKbqQ'
      controls
      className='rounded-xl w-full h-full'
      blurDataURL='/menuImages/burgerBg.png'
      accentColor='#14B082'
    />
```

But I still face this error :
![image](https://github.com/muxinc/next-video/assets/77692478/d7309345-4b4c-4532-949d-f994a6d34843)

I have videos folder inside my public folder, I tried to move it to my folder root directory, but still same problem

**Comment by yassineatik** [comment]
The json file is created in videos folder, but it has error in the status:
```JSON
{"status":"error","originalFilePath":"https://www.youtube.com/watch?v=RqitwhLKbqQ","externalIds":{"assetId":"75UDGAolJv2K1GTFSD19dT7kYfpJfRCyQK1y028HnXm8","playbackId":"p5eTwD4xsfMI01KxUy00A7UlyisOiHjhsTQ3F7TiPyswc"},"createdAt":1700940175111,"updatedAt":1700940179568,"error":{"type":"invalid_input","messages":["The input file was not a valid video or audio file."]}}
```

**Comment by luwes** [comment]
thanks for the feedback! 

this is expected because the URL you provide is not a video source URL like an .mp4 for example.

Only remote video sources or local video files are supported for processing by next-video currently.

If it's your YT video, try adding the original video source in the videos folder and import it in your app.
