### ISSUE TITLE
SyntaxError: The requested module 'next-video' does not provide an export named 'withNextVideo'

### ISSUE THREAD

**Issue by sbkobaidze** [muxinc/next-video#122]
After I installed next-video and tried to run the project it returns this error in next.config.js `SyntaxError: The requested module 'next-video' does not provide an export named 'withNextVideo'`

**Comment by sbkobaidze** [comment]
What i noticed is that in next.config.js `npx video init` imports `import { withNextVideo } from 'next-video`' instead of `import { withNextVideo } from 'next-video/process';
`

**Comment by luwes** [comment]
thanks for reporting, this still seems to be an issue with `next.config.mjs`

**Comment by luwes** [comment]
this should be fixed in https://github.com/muxinc/next-video/releases/tag/v0.10.0
