### ISSUE TITLE
mux Autorization Error 

### ISSUE THREAD

**Issue by WebDevZakaria** [muxinc/next-video#130]
when i use the command   npx next-video sync   i had this error :

    Failed to load next.config.js or next.config.mjs
    ✗ Error creating a Mux Direct Upload
    AuthenticationError: 401 {"error":{"type":"unauthorized","messages":["Unauthorized request"]}}

any help please ?

**Comment by luwes** [comment]
thanks for the reporting! I think it's because the Mux env variables are not found.
did you put your `MUX_TOKEN_ID` and `MUX_TOKEN_SECRET` in your env file?

**Comment by luwes** [comment]
closing until picked back up
