### ISSUE TITLE
"This Suspense boundary received an update before it finished hydrating."

### ISSUE THREAD

**Issue by NicHaley** [muxinc/next-video#135]
When rendering the `<Video ... />` component I receive the following error:

"Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition."

I am using Next 14.0.2 and React 18.2.0.

Here is a simplified snippet:
```
import Video from "next-video";
import Video1 from "videos/vid.mp4";


export function Component() {
...
return <Video className="inline" src={Video1} />;
}
```

Let me know if I can provide any more context.

**Comment by luwes** [comment]
closing until confirmed
