### ISSUE TITLE
Next video + AWS Amplify error

### ISSUE THREAD

**Issue by alejandrohg1** [muxinc/next-video#136]
I run into an issue using the amazon-s3 provider on next-video, when I try to deploy the application using aws amplify, the enviroment variables can not have the reserved prefix AWS , is there a way to fix this problem in the next versions o how can I change it so it works on amazon, 

![IssuesAws](https://github.com/muxinc/next-video/assets/59666985/77aa1997-e9f7-4a4c-a5b6-7dcee14fffe0)

**Comment by luwes** [comment]
thanks for reporting this!

I'm a bit baffled that there is no way to set AWS prefixed env variables in an AWS service but I can't find any explanation so far so the PR by @DewinU seems like a good workaround.
