### ISSUE TITLE
What are Client.webpack.lock & server.webpack.lock?

### ISSUE THREAD

**Issue by devwilliamy** [muxinc/next-video#150]
Hi,

I'm new to next-video and I'm trying to use it alongside `vercel-blob`. 

I've set up my `next.config.js` like so:
```
module.exports = withNextVideo(nextConfig, {
  provider: 'vercel-blob',
});
```

But I've noticed that I now have these two files: `client-webpack-lock` and `server-webpack-lock`.

I was curious what they were for and if I should commit them into my version control? 

They seem to be related to the video I have on Vercel blob. 

Also when I try to look at the video I get a warning saying it's not processing, that I should try to run `next-video sync` and that it's playing from the source. Is this as intended? When I try to run `next-video sync` it says `Failed to load next.config.js` even though I ran `npx next-video init` and confirmed it's in my root. I did try doing `mux` before but I took all my old `.json` and `.mp4` out of the `/videos` folder but I still get `An unknown error occurred MuxError: The MUX_TOKEN_ID environment variable is missing or empty; either provide it, or instantiate the Mux client with an tokenId option, like new Mux({ tokenId: 'my tokenId' }).`. Do I need to clear some hidden folders or does just not operate without the mux env variables?

**Comment by luwes** [comment]
thanks for the feedback, `client-webpack-lock` and `server-webpack-lock` is generated by Webpack.
I'm not 100% sure what they do but they shouldn't be committed to version control.

---

yes, you should have to run `next-video sync` in the root of you project once you added the required env variable for Vercel blob `BLOB_READ_WRITE_TOKEN`

here is an online example with Vercel blob 
https://codesandbox.io/p/devbox/next-video-vercel-blob-w6wwqw?file=%2Fapp%2Fpage.js%3A14%2C17

let's continue discussion in 1 issue. closing here.
