### ISSUE TITLE
`undefined` value on Network tab when the player starts to play the video

### ISSUE THREAD

**Issue by jzambrano12** [muxinc/next-video#166]
Well basically this is happening in my new NextJs 14 project using `next-video` library. 
<hr/> 

![image](https://github.com/muxinc/next-video/assets/27393245/22bda578-e855-4f74-8df4-20d379ffeb66)

<hr/> 
I'm using a CDN to play the video from there. This is my component:

```
import Video from 'next-video';

interface HostVideoProps {
  params: {
    id: string;
  };
}

export default function HostVideo({ params }: HostVideoProps) {
  const { id } = params;

  return (
    <Video
      src={`https://${process.env.HOST_CDN}/${id}/playlist.m3u8`}
      className="w-screen h-screen"
    />
  );
}
```

The request appears every second in my browser even though the video is paused.

**Comment by luwes** [comment]
thanks for reporting! 

this use case is not yet considered but we might add a workaround for `.m3u8` sources.

next-video is intended to be used with raw video sources, .mp4, .mov, etc. and it uploads them to the providers.

it seems that you're videos are already uploaded and processed?

**Comment by luwes** [comment]
yes, it tries to process the string based video source you provide to the NextVideo component 
see https://github.com/muxinc/next-video?tab=readme-ov-file#alternative

I will add an exception for `.m3u8` files soon so this doesn't happen.

(note the polling is only in development mode)

**Comment by jzambrano12** [comment]
Great!! @luwes thanks!
