### ISSUE TITLE
Sync error: ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by dninomiya** [muxinc/next-video#196]
Following the documentation, I added demo.mp4 to /videos and ran the sync command, but an error occurred

```log
bunx next-video sync -w
✗ An unknown error occurred TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.relative (node:path:1196:5)
    at file:///Users/nino/Downloads/my-app/node_modules/next-video/dist/cli/sync.js:51:34
    at Array.map (<anonymous>)
    at Object.handler (file:///Users/nino/Downloads/my-app/node_modules/next-video/dist/cli/sync.js:50:63) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

It was the same with `npx`

[demo-video.mp4.zip](https://github.com/muxinc/next-video/files/14428847/demo-video.mp4.zip)

I'm running a pure nextjs application.

1. bunx create-next-app@latest
2. bun add next-video
3. bunx next-video init
4. bunx next-video sync

✅ The mux key is set in env. Node.js v19.7.0

---

Thank you for your support!

**Comment by luwes** [comment]
how does your next.config.js look like?

**Comment by dninomiya** [comment]
Here it is. It follows the latest Next.js initialization flow and initializes next-video in a plain state without any modifications.

**next.config.mjs** 
```mjs
import { withNextVideo } from "next-video/process";
/** @type {import('next').NextConfig} */
const nextConfig = {};

export default withNextVideo(nextConfig);
```

Full file
[video-test.zip](https://github.com/muxinc/next-video/files/14519331/video-test.zip)

Thank you for your support!

**Comment by luwes** [comment]
thank you, the config looks good

does it work with `npx ...`?

**Comment by yassinemab** [comment]
I'm also running into this problem... Any fixes yet?

**Comment by luwes** [comment]
hmm must be something with the code below

do you have a `/videos` folder? what's in it?
can you try an explicit `dir` in the command?

`npx next-video sync --dir videos`


```js
  const directoryPath = path.join(cwd(), argv.dir as string);

  try {
    const dirents = await readdir(directoryPath, {
      recursive: true,
      withFileTypes: true,
    });

    // Filter out directories and get relative file paths.
    const files = dirents
      .filter((dirent) => dirent.isFile())
      .map((dirent) =>
        path.join(path.relative(directoryPath, dirent.path), dirent.name)
      );
```

**Comment by nicitaacom** [comment]
> hmm must be something with the code below
> 
> do you have a `/videos` folder? what's in it? can you try an explicit `dir` in the command?
> 
> `npx next-video sync --dir videos`
> 
> ```js
>   const directoryPath = path.join(cwd(), argv.dir as string);
> 
>   try {
>     const dirents = await readdir(directoryPath, {
>       recursive: true,
>       withFileTypes: true,
>     });
> 
>     // Filter out directories and get relative file paths.
>     const files = dirents
>       .filter((dirent) => dirent.isFile())
>       .map((dirent) =>
>         path.join(path.relative(directoryPath, dirent.path), dirent.name)
>       );
> ```

I want to keep my video in ./public folder
I have only 1 video and don't want create videos folder for 1 video
I tried with `npx next-video sync --dir public`

**Comment by dninomiya** [comment]
@luwes 
I tried all the flows with npx but got the same error.

<img width="1012" alt="image" src="https://github.com/muxinc/next-video/assets/5842851/0838c3dd-65fc-4667-abc7-8483467695af">

**Comment by luwes** [comment]
thank you, I'll have a deeper look soon. 
normally it should do nothing because there's no video files in the videos folder

**Comment by luwes** [comment]
I reproduced it, it happens on Node v16. will fix that, I think we want to still support v16
