### ISSUE TITLE
Vulnerability in next-video dependency @vercel/blob

### ISSUE THREAD

**Issue by arndvs** [muxinc/next-video#210]
Hello next-video maintainers,

I hope this message finds you well. I am reaching out to inform you about a potential vulnerability in the next-video package caused by its dependency on @vercel/blob.

While using next-video in my project, I encountered the following error:

```
undici <=5.28.2 Undici proxy-authorization header not cleared on cross-origin redirect in fetch - https://github.com/advisories/GHSA-3787-6prv-h9w3
fix available via `npm audit fix --force`
Will install next-video@0.8.6, which is a breaking change

node_modules/@vercel/blob/node_modules/undici
  @vercel/blob 0.0.3 - 0.22.1-0cb7edd4-20240221003206
  Depends on vulnerable versions of undici

node_modules/@vercel/blob
next-video >=0.9.0
Depends on vulnerable versions of @vercel/blob

node_modules/next-video
```

It appears that @vercel/blob, a dependency of next-video, relies on a vulnerable version of undici (<=5.28.2). The vulnerability is related to the proxy-authorization header not being cleared on cross-origin redirects in fetch requests. More information about this vulnerability can be found at https://github.com/advisories/GHSA-3787-6prv-h9w3.

Running npm audit fix --force suggests installing next-video@0.8.6, which is a breaking change. However, I wanted to bring this to your attention so that you can investigate the issue further and potentially update the @vercel/blob dependency in next-video to a version that relies on a patched version of undici.

**Comment by luwes** [comment]
thanks for reporting! this was fixed in https://github.com/muxinc/next-video/pull/214 I believe
