### ISSUE TITLE
Cannot read properties of undefined (reading 'isAvailable'

### ISSUE THREAD

**Issue by dragos99** [muxinc/next-video#211]
Just embedding a video throws this error on the console everytime.

`Cannot read properties of undefined (reading 'isAvailable'`

```
import introVideo from '/videos/intro.mp4';

<Video
       accentColor="#14b5ff"
       src={introVideo}
       poster={'/landing-thumbnail.webp'}
       className="w-full aspect-video"
/>
```

**Comment by luwes** [comment]
do you have an import for the `Video` component?

could you make a reproduction online?

here is a working Codesandbox you could fork
https://codesandbox.io/p/devbox/next-video-mux-j9nn73?file=%2Fapp%2Fpage.js%3A21%2C1

here is also a working next.js site 
https://github.com/muxinc/next-video/blob/main/examples/default-provider/app/page.tsx
https://next-video-demo.vercel.app/

**Comment by jakubmas** [comment]
Hey, I'm facing the same issue but it happens only on small screens. 
I am using next-video: "^1.1.0", with next: "14.1.4", hosts videos on MUX and my code looks like this:
`import NextVideo from 'next-video';
import sample from '@/videos/stock-video.mp4';

export const TestVideo = () => {
  return (
            <div className="rounded-2xl border-4 border-black w-[800px] bg-red-200">
              <NextVideo
                src={sample}
                autoPlay={true}
                muted
                loop
                playsInline
                controls={false}
                style={{
                  aspectRatio: 16 / 9,
                }}
              />
            </div>
  );
};
`
As I said the error "TypeError: Cannot read properties of undefined (reading 'isAvailable')" (app-pages-browser)/node_modules/@mux/mux-video/dist/index.mjs (39:4688) happens only on a mobile screens.
