### ISSUE TITLE
✗ An unknown error occurred TypeError: Cannot read properties of undefined (reading 'provider')

### ISSUE THREAD

**Issue by econics** [muxinc/next-video#212]
Hi,

I read all your docs and have tried to integrate Mux into my Next.js project and can't make it work. I get this error :

- NEXT STEP: Set up remote storage
- https://next-video.dev/docs#remote-storage-and-optimization

PS C:\GanG\website> npx next-video sync
+ Found 1 unprocessed video
- Processing file: work.mp4
✗ An unknown error occurred TypeError: Cannot read properties of undefined (reading 'provider')
at createAsset (file:///C:/GanG/website/node_modules/next-video/dist/assets.js:40:27)
at async newFileProcessor (file:///C:/GanG/website/node_modules/next-video/dist/cli/sync.js:62:24)
at async Promise.all (index 0)
at async Object.handler (file:///C:/GanG/website/node_modules/next-video/dist/cli/sync.js:88:24)

PS C:\GanG\website>

and this is my package.json : {
"name": "next-app-template",
"version": "0.0.1",
"private": true,
"scripts": {
"dev": "next dev & npx next-video sync -w",
"build": "next build",
"start": "next start",
"lint": "next lint"
},
"dependencies": {
"@mux/mux-player": "^2.4.0",
"@nextui-org/button": "2.0.26",
"@nextui-org/code": "2.0.24",
"@nextui-org/input": "2.1.16",
"@nextui-org/kbd": "2.0.25",
"@nextui-org/link": "2.0.26",
"@nextui-org/navbar": "2.0.27",
"@nextui-org/react": "^2.2.10",
"@nextui-org/snippet": "2.0.30",
"@nextui-org/switch": "2.0.25",
"@nextui-org/system": "2.0.15",
"@nextui-org/theme": "2.1.17",
"@prisma/client": "^5.11.0",
"@react-aria/ssr": "^3.8.0",
"@react-aria/visually-hidden": "^3.8.6",
"@types/node": "20.5.7",
"@types/react": "^18.2.71",
"@types/react-dom": "^18.2.22",
"@vercel/blob": "^0.22.1",
"@vercel/postgres": "^0.7.2",
"autoprefixer": "10.4.16",
"busboy": "^1.6.0",
"clsx": "^2.0.0",
"eslint-config-next": "^14.1.4",
"figures": "^6.1.0",
"framer-motion": "^10.18.0",
"intl-messageformat": "^10.5.0",
"next": "^14.1.4",
"next-images": "^1.8.5",
"next-themes": "^0.2.1",
"next-video": "^0.16.2",
"postcss": "8.4.31",
"prisma": "^5.11.0",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-hot-toast": "^2.4.1",
"tailwind-variants": "^0.1.18",
"tailwindcss": "3.3.5",
"zod": "^3.22.4"
},
"devDependencies": {
"@types/busboy": "^1.5.3",
"@types/next": "^9.0.0",
"eslint": "^8.57.0",
"eslint-config-prettier": "^9.1.0",
"typescript": "^5.4.3"
}
}
Please advise how to solve this. I've spent days combing through forums and talking to Vercel

**Comment by luwes** [comment]
how does your next.config.js look like?

**Comment by econics** [comment]
const { withNextVideo } = require('next-video/process')

/** @type {import('next').NextConfig} */
const nextConfig = {}

module.exports = nextConfig

**Comment by luwes** [comment]
it should look like this

```js
/** @type {import('next').NextConfig} */
const { withNextVideo } = require('next-video/process');

const nextConfig = {}; // Your current Next Config object

module.exports = withNextVideo(nextConfig);
```

notice the `withNextVideo(nextConfig)` being used at the bottom.

**Comment by luwes** [comment]
yes, ESM imports and bundler moduleResolution are the defaults I believe in the latest Next.js 

which package is erroring then?
