### ISSUE TITLE
Disable tracking/analytics

### ISSUE THREAD

**Issue by garviand** [muxinc/next-video#231]
I am using the `BackgroundVideo` component and I can't figure out how to disable the POST requests to "https://inferred.litix.io".

I tried to look through the docs and other issues but I didn't find anything, hope I'm not missing something obvious!

**Comment by luwes** [comment]
thanks for the feedback, this should be available in v1.0.1

here's an example with `disableTracking` enabled
https://next-video-demo.vercel.app/background-video
