### ISSUE TITLE
Infinite GET Request to /api/video

### ISSUE THREAD

**Issue by Rablidad** [muxinc/next-video#246]
Hi, Im using this code to load a video:

`<BackgroundVideo
        src="/videos/nba.mp4"
      >
    ...
</BackgroundVideo>`

and for some reason it sends a GET request to /api/video all the time

![image](https://github.com/muxinc/next-video/assets/38145996/1e0e0528-5f14-4ea6-ad7c-b5c5cec67a80)

how to solve this?

**Comment by luwes** [comment]
related #250
this is not really a bug but I see you're trying to use only the video player which is not officially supported yet.
we're going to add this soon.

**Comment by abduraufsherkulov** [comment]
![CleanShot 2024-05-13 at 14 24 15](https://github.com/muxinc/next-video/assets/17489128/891e057e-0b93-49d9-8e22-b0f1e8dbdae2)
This is happening even when mux is integrated

**Comment by TestCK** [comment]
This even happen after deleting the package, how can I stop it?. 

I deleted the package, I delete the project and git clone again, still it  keeps sending request

**Comment by luwes** [comment]
there's a `next-video/player` and `next-video/background-player` export available in the latest release 1.1.0
these are just the player and will not attempt to upload the video...

example:
next-video-demo.vercel.app/player-only
main/examples/default-provider/app/(default)/player-only/page.tsx
