### ISSUE TITLE
Add Option To Not Upload Video If Using Remote Source String

### ISSUE THREAD

**Issue by devwilliamy** [muxinc/next-video#250]
Let me know if this completely defeats the purpose of next-video, but I've been given a requirement to get the video from one of our servers through a remote URL.

I'm following this: https://next-video.dev/docs#remote-videos

And as the docs say, in doing so will have the video process and be uploaded to my hosting provider (I'm using Vercel Blob).
It does feel very weird to have the videos saved on a server to be reuploaded to another server so I was wondering if it's possible to just read from the source string or if that just defeats the purpose of using next-video and I should consider another video player.

I'm also running into another issue where if I don't have the JSON for the video, it won't play. For some context, I'm going to be uploading videos to this server, and updating my database with video links, and my website will get the source string but from the database. But in order for me to have the video play, I have to get this to upload on my local first, but I can't always do that because maybe there will be 100 videos added. Is there a workaround for this or something I'm misunderstanding? 

Thank you!

**Comment by luwes** [comment]
Thanks for this feedback! we're going to make this possible, seems this is often requested.

**Comment by devwilliamy** [comment]
Thanks @luwes ! Sucks I have to move off of it for the time being, but will keep an eye out for the PR to switch back!

**Comment by luwes** [comment]
there's a `next-video/player` export available in the latest release 1.1.0

example:
https://next-video-demo.vercel.app/player-only
https://github.com/muxinc/next-video/blob/main/examples/default-provider/app/(default)/player-only/page.tsx
