### ISSUE TITLE
TypeScript does not recognize the types for the next video.

### ISSUE THREAD

**Issue by isrezaei** [muxinc/next-video#258]
When I imported the next-video package in my component, I got an error that said S2307: Cannot find module 'next-video' or its corresponding type declarations. How can I fix that? 
I installed the package according to the document.

My problems
![Screenshot 2024-05-26 183905](https://github.com/muxinc/next-video/assets/77073972/612db2aa-e9ef-49ac-b0c1-5e8319e171af)

Also 
In the console log, I received many 404 errors! I don't know why I got this error after playing the video!
![Screenshot 2024-05-26 183944](https://github.com/muxinc/next-video/assets/77073972/a46b0d1d-7127-4bd0-aaf5-935b115b04cb)

**Comment by luwes** [comment]
@isrezaei are you still running into this issue? it's possible you might need to restart the TS server in VS code.

if you want to use string video sources which don't need uploading you can use the player export added in v1.1.0

example:
https://next-video-demo.vercel.app/player-only
https://github.com/muxinc/next-video/blob/main/examples/default-provider/app/(default)/player-only/page.tsx

**Comment by pedroviniciusn** [comment]
Well, I just solved it, I just had to put tsconfig's moduleResolution as bundler and then it worked, I still don't know if this could break other things in my project, I hope not.

**Comment by luwes** [comment]
yes, that's nextjs default nowadays. `"moduleResolution": "bundler",`

thanks for following up here!
