### ISSUE TITLE
.env.local vars don't work

### ISSUE THREAD

**Issue by heff** [muxinc/next-video#26]
The readme currently points to using .env.local to store Mux environment vars, however when next-video scripts run those vars are not available to them.

Exporting the vars manually gets around the issue temporarily.

**Comment by AdamJaggard** [comment]
Maybe we can follow the same alg that nextjs is using for loading env vars, so that we load the env files in the correct order, in the correct environment etc: https://github.com/vercel/next.js/blob/canary/packages/next-env/index.ts
