### ISSUE TITLE
Error when processing files

### ISSUE THREAD

**Issue by Roeck** [muxinc/next-video#270]
When running npx next-video sync, it keeps returning:
```
 - Processing file: teaser.MOV
✗ An unknown error occurred TypeError: Cannot read properties of undefined (reading 'provider')
```
Although, the structure and upload setup seems correct. Thoughts?

**Comment by heff** [comment]
Hi 👋 Which provider are you using? (default = Mux)

@luwes any initial thoughts?

**Comment by Roeck** [comment]
Hi @heff , yes, I'm using Mux as the provider. More specifically, I've been following this tutorial right here: https://www.youtube.com/watch?v=8guP6F56TPk

**Comment by luwes** [comment]
could you try out the steps from here?
https://github.com/muxinc/next-video/issues/251#issuecomment-2112789735

> could you make a reproduction online?
> 
> is it on Windows or Mac?
> what is your module resolution in tsconfig?
> 
> here is a working Codesandbox you could fork
> [codesandbox.io/p/devbox/next-video-mux-j9nn73?file=%2Fapp%2Fpage.js%3A21%2C1](https://codesandbox.io/p/devbox/next-video-mux-j9nn73?file=%2Fapp%2Fpage.js%3A21%2C1)
> 
> here is also a working next.js site
> [main/examples/default-provider/app/page.tsx](https://github.com/muxinc/next-video/blob/main/examples/default-provider/app/page.tsx?rgh-link-date=2024-05-15T15%3A01%3A22Z)
> [next-video-demo.vercel.app](https://next-video-demo.vercel.app/)
> 
> related:
> https://github.com/muxinc/next-video/issues/212

related #251

**Comment by Roeck** [comment]
@luwes Solved. I appreciate the help

**Comment by Roeck** [comment]
@luwes Solved! I appreciate the help
