### ISSUE TITLE
Cannot play a BackgroundVideo on Safari/Chrome for iOS

### ISSUE THREAD

**Issue by RosarioAleCali** [muxinc/next-video#274]
Hi there, I am having a little bit of trouble playing a BackgroundVideo on Safari/Chrome for iOS.

Video plays fine on Safari/Chrome for MacOS as far as I can tell. It also plays fine on Android devices from what I'm told.

I am using Mux as my provider.

This is my component:
```JS
import BackgroundVideo from 'next-video/background-video';
import apartmentVideo from '/videos/background-video.mp4?thumbnailTime=0';

const Hero = () => {
  return (
      <BackgroundVideo src={apartmentVideo} />
  );
}

export default Hero;
```

This is my config:
```JS
import { withNextVideo } from "next-video/process";
import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin();

/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    GOOGLE_PLACES_API_KEY: process.env.GOOGLE_PLACES_API_KEY,
    PLACE_ID: process.env.PLACE_ID,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'lh3.googleusercontent.com',
        pathname: '**',
      },
    ],
  },
};

export default withNextIntl(withNextVideo(nextConfig));
```

Let me know what things I could look into to get this working or what else you'd need from me!
```[tasklist]
### Tasks
```

**Comment by luwes** [comment]
could you provide a demo / example online? 
can you see the playback-id of the asset? it's uploaded to Mux?

**Comment by RosarioAleCali** [comment]
@luwes Here's the live website: https://airam-apartment.vercel.app/

I can see the `playbackId` in the .json file and I can see the provider is set to Mux.
