### ISSUE TITLE
Undefined config causing many GETs to /undefined?url=[actual url]

### ISSUE THREAD

**Issue by Cheese-Echidna** [muxinc/next-video#290]
I am building a content (mostly video) streaming app in NextJS (think plex but worse) and have been trying to use NextVideo for video playback.

When I try and play a video through the player, it stalls out and after a while the video stops playing.

Looking at the console, I see a lot (about 1 every 2s) of requests that are returning 404. 

The requests are going to /undefined?url= followed by the actual url of the video content.

Checking out the source of the error, it seems to be coming from video-loader.js

`let requestUrl = '${config2.path}?url=${encodeURIComponent('${src}')}';`

I'm guessing config2 is undefined or null.

Is there anything I can do on my end to prevent this issue. I am literally just returning a div containing `<NextVideo src={myVideo}/>` where myVideo is a the path to a video.

Also, your bug report form 404s
https://github.com/muxinc/next-video/blob/dabac8fd37f46c5508030248ac4f59b9253bfd41/.github/CONTRIBUTING.md#issues
Sends you to:
https://github.com/muxinc/next-video/blob/dabac8fd37f46c5508030248ac4f59b9253bfd41/issues/new/choose

Thanks

**Comment by kinjal017** [comment]
I am also getting the same error and behavior, it would be nice to have the fix for these soon.

**Comment by lh15** [comment]
Same here

Seems like some config is supposed to be set here

**Comment by lh15** [comment]
Is this only supposed to work for mux?

https://github.com/muxinc/next-video/blob/dabac8fd37f46c5508030248ac4f59b9253bfd41/src/components/video-loader.ts#L31

**Comment by luwes** [comment]
thanks for reporting!

how does your `next.config.(m)js` look like?

is this setting set in `tsconfig.json`? `"moduleResolution": "bundler",`

**Comment by luwes** [comment]
@marcobarbosa this is expected. 

See **Remote videos with string source URL** at https://github.com/muxinc/next-video#remote-videos

If you like to play remote string sources with no uploading/processing via the request handler you can use the player only imports. See https://github.com/muxinc/next-video#player-only-demo

**Comment by matheusmcz** [comment]
Hi guys, i have the same issue. I'm using Custom Player with custom controls and remote video url provided by a BFF and all seems working fine, but every 2s this requests have been called and returning 404 (same thing that @marcobarbosa send).
There is some setting to add in next.config or ts.config?

My next config have the basic setup:
`
import { withNextVideo } from "next-video/process"; 
export default withNextVideo(nextConfig);
`

ts.config aready have `"moduleResolution": "bundler",`

**Comment by luwes** [comment]
@matheusmcz see my answer above.

> If you like to play remote string sources with no uploading/processing via the request handler you can use the player only imports. 
See https://github.com/muxinc/next-video#player-only-demo
