### ISSUE TITLE
"No such file or directory" when deploying to Vercel

### ISSUE THREAD

**Issue by focux** [muxinc/next-video#89]
First of all, you've built an awesome and very useful library, it is so nice, thank you!

Now, continuing with my bug report, I was trying to deploy a project using `next-videos` to Vercel and got this error after building:

```
Error: ENOENT: no such file or directory, mkdir '/vercel/output/static/_videos'
```

<img width="1100" alt="image" src="https://github.com/muxinc/next-video/assets/3316818/2f4861d9-23ba-4429-832f-876dea6bfc7c">

However, when I build the project locally, it works well and I don't get any error. I suspect that this error might be related to the deploying phase of Vercel after the project is built.

**Comment by focux** [comment]
Removing `_videos` file from the `public` folder fixed it. I'm not even sure how that file got there 😅   — thanks anyways

**Comment by luwes** [comment]
Thanks for reporting!

We should automatically clean this up or add it to gitignore by default.
It's a temporary symlink needed to load the local video until the asset is finished processing.

Will keep you updated!
