### ISSUE TITLE
Double package install with npx flow

### ISSUE THREAD

**Issue by heff** [muxinc/next-video#93]
Starting with a fresh next app then `npx next-video init`, it first says it needs to install next-video, then after it apparently installs it, it then asks again.

![image](https://github.com/muxinc/next-video/assets/166/68db8699-6050-4e59-9e65-0d550392a98a)

**Comment by luwes** [comment]
the first question is coming from the `npx` command. it installs next-video in a cache or globals node_modules (not 100% sure) to run the CLI command and then it goes over to the next-video workflow.

we can change the docs and add `npx -y next-video init` or `npx --yes next-video init` which will skip the first question

**Comment by heff** [comment]
Closing because I think we're ok with this for now.
