### ISSUE TITLE
`import Video from 'next-video'` not working properly in a monorepo setup

### ISSUE THREAD

**Issue by liam-germain** [muxinc/next-video#97]
Here is the error I am getting; 'Type error: Cannot find module 'next-video' or its corresponding type declarations.'

I am able to run the project locally and watch the video in my browser but the project still throws errors over this and I am not able to perform a production build of the application.

**Comment by codeship89** [comment]
Having the same issues here..

**Comment by Rychillie** [comment]
I'm having the same issue, but I'm not in a monorepo!

**Comment by Rychillie** [comment]
Fixed changing my `moduleResolution` to **"bundler"** on my `tsconfig.json` file

**Comment by luwes** [comment]
I'm not sure this is related to monorepo's. Can you confirm `next-video` is installed in the Next.js app's dependencies?

**Comment by w4jo** [comment]
> Fixed changing my `moduleResolution` to **"bundler"** on my `tsconfig.json` file

The same issue for me, but this breaks another package import.
Eg:
```
Could not find a declaration file for module '@calcom/embed-react'. '/Users/wajo/Code/ozoit/node_modules/.pnpm/@calcom+embed-react@1.3.0_react-dom@18.2.0_react@18.2.0/node_modules/@calcom/embed-react/dist/Cal.es.mjs' implicitly has an 'any' type.
  There are types at '/Users/wajo/Code/ozoit/apps/web/node_modules/@calcom/embed-react/dist/embed-react/src/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@calcom/embed-react' library may need to update its package.json or typings.ts(7016)
```

**Comment by eoinotoole** [comment]
One more for this issue 🥲 Not a mono repo, declaration files created as specified in the docs

**Comment by luwes** [comment]
hmm this is tough one to figure out. any chance anyone could provide a code sandbox replicating the issue?
is it still happening with v0.10.1?

I have a working example here https://github.com/luwes/next-video-app

**Comment by luwes** [comment]
closing in favor of https://github.com/muxinc/next-video/issues/133
the monorepo topic is handled in https://github.com/muxinc/next-video/issues/84
