### ISSUE TITLE
 'next-video' does not provide an export named 'withNextVideo'

### ISSUE THREAD

**Issue by bradbitler** [muxinc/next-video#98]
I'm receiving the following error when I try to run the project locally after using the setup wizard. Any ideas?

> import { withNextVideo } from "next-video";
>          ^^^^^^^^^^^^^
> SyntaxError: The requested module 'next-video' does not provide an export named 'withNextVideo'

**Comment by luwes** [comment]
thanks for the feedback! could you confirm `next-video` is installed as one of your dependencies in package.json? thanks

**Comment by luwes** [comment]
also have a look at this working minimal example https://github.com/luwes/next-video-app

**Comment by luwes** [comment]
it looks like there is an issue with ESM, thanks for reporting! we have a PR open to fix it.

**Comment by nekochan0122** [comment]
I think the types is also missing.

![image](https://github.com/muxinc/next-video/assets/47508893/c5a0719f-0fbd-4dbf-bb4b-7a360b78f8c4)

![image](https://github.com/muxinc/next-video/assets/47508893/35cf910c-82a4-476b-896f-e84796935e82)

**Comment by luwes** [comment]
Thanks for the feedback y'all! Could you try out version v0.9.0 and see if the issue is resolved?

**Comment by nekochan0122** [comment]
The type issue is resolved. And I have a type suggestion, the `videoConfig` should be optional.

![image](https://github.com/muxinc/next-video/assets/47508893/e5299cb2-4bef-4e36-89f0-89e4c1d749c6)

**Comment by nekochan0122** [comment]
I make a PR for this, please check it out #106
